name: t_stats
description: A micro-library for statistics, especially for comparing samples.
version: 2.0.0
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://github.com/filiph/t_stats

environment:
  sdk: '>=1.23.0 <3.0.0'

dependencies:
  quiver: ^2.0.0

dev_dependencies:
  test: ^1.3.0

executables:
  t_stats:
