name: t_stats
description: A micro-library for statistics, especially for comparing samples.
version: 3.1.0
homepage: https://github.com/filiph/t_stats

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.0.0

executables:
  t_stats:
