name: t_stats
description: A micro-library for statistics, especially for comparing samples.
version: 1.1.2
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://github.com/filiph/t_stats

environment:
  sdk: '>=1.18.0 <2.0.0'

dependencies:
  bignum: ^0.1.0
  quiver: ^0.26.2

dev_dependencies:

  test: '>=0.12.0 <0.13.0'

executables:
  t_stats:
