name: t_stats
description: A micro-library for statistics, especially for comparing samples.
version: 3.0.0
homepage: https://github.com/filiph/t_stats

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.7

executables:
  t_stats:
