name: t_stats
description: A micro-library for statistics, especially for comparing samples.
version: 1.0.0
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://github.com/filiph/t_stats

environment:
  sdk: '>=1.18.0 <2.0.0'

dev_dependencies:
  bignum: ^0.1.0
  test: '>=0.12.0 <0.13.0'

executables:
  t_stats: