name: t_stats
description: A micro-library for statistics, especially for comparing samples.
version: 2.1.1
homepage: https://github.com/filiph/t_stats

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  quiver: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.3.0

executables:
  t_stats:
