name: t_stats
description: A micro-library for statistics, especially for comparing samples.
version: 3.0.0-nullsafety.0
homepage: https://github.com/filiph/t_stats

environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'

dependencies:
  quiver: ^3.0.0-nullsafety.3

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.16

executables:
  t_stats:
